In [1]:
using DrWatson;
@quickactivate "MATH361Lectures";
import MATH361Lectures
using LinearAlgebra

In [52]:
A = [-1 2 3;3 -1 2;-1 0 1;0 1 1;-1 -1 1]

5×3 Matrix{Int64}:
 -1   2  3
  3  -1  2
 -1   0  1
  0   1  1
 -1  -1  1

In [53]:
m,n = size(A);
e1 = [1;0;0;0;0];
z = A[:,1];
v = norm(z,2)*e1 - z
β = 2 / (v'*v);
P = Matrix{Float64}(I,m,m) - β * (v * v') 

5×5 Matrix{Float64}:
 -0.288675  0.866025  -0.288675   0.0  -0.288675
  0.866025  0.418007   0.193998   0.0   0.193998
 -0.288675  0.193998   0.935334   0.0  -0.0646659
  0.0       0.0        0.0        1.0   0.0
 -0.288675  0.193998  -0.0646659  0.0   0.935334

In [54]:
P*A

5×3 Matrix{Float64}:
  3.4641       -1.1547    0.288675
 -2.22045e-16   1.12005   3.82209
  1.38778e-17  -0.706682  0.392638
  0.0           1.0       1.0
  0.0          -1.70668   0.392638

In [55]:
P' == P

true

In [56]:
P*P ≈ round.(abs.(P*P))

true

In [57]:
round.(abs.(P*P))

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [58]:
function hhzero(z)
    m = size(z)[1];
    e1 = zeros(m);
    e1[1] = 1.0;
    v = norm(z,2)*e1 - z;
    β = 2 / (v'*v);
    P = Matrix{Float64}(I,m,m) - β * (v * v')
end

hhzero (generic function with 1 method)

In [59]:
QA = P*A

5×3 Matrix{Float64}:
  3.4641       -1.1547    0.288675
 -2.22045e-16   1.12005   3.82209
  1.38778e-17  -0.706682  0.392638
  0.0           1.0       1.0
  0.0          -1.70668   0.392638

In [60]:
hhzero(QA[2:end,2])

4×4 Matrix{Float64}:
  0.470514  -0.296866  0.420084  -0.71695
 -0.296866   0.833557  0.235527  -0.40197
  0.420084   0.235527  0.666714   0.568814
 -0.71695   -0.40197   0.568814   0.0292158

In [61]:
A

5×3 Matrix{Int64}:
 -1   2  3
  3  -1  2
 -1   0  1
  0   1  1
 -1  -1  1

In [62]:
function hhqr!(A)
    m,n = size(A);
    Q = Matrix{Float64}(I,m,m);
    for k = 1:n
        z = A[k:end,k];
        Q[k:m,k:m] = hhzero(z);
        A = Q*A;
    end
    Q = Q';
    return Q, A
end

hhqr! (generic function with 1 method)

In [63]:
Q, A = hhqr!(A);