In [1]:
using DrWatson;
@quickactivate "MATH361Lectures";
import MATH361Lectures
using LinearAlgebra

In [2]:
A = [-1 0;0 2;1 1]

3×2 Matrix{Int64}:
 -1  0
  0  2
  1  1

In [3]:
z = A[:,1]

3-element Vector{Int64}:
 -1
  0
  1

In [4]:
e1 = [1;0;0]

3-element Vector{Int64}:
 1
 0
 0

In [5]:
v = norm(z,2)*e1 - z

3-element Vector{Float64}:
  2.414213562373095
  0.0
 -1.0

In [6]:
P = Matrix{Float64}(I,3,3) - (2/(v'*v))*(v*v')

3×3 Matrix{Float64}:
 -0.707107  0.0  0.707107
  0.0       1.0  0.0
  0.707107  0.0  0.707107

In [7]:
Ph = [1 - (1+sqrt(2))^2/(2+sqrt(2)) 0 (1+sqrt(2))/(2+sqrt(2));0 1 0;(1+sqrt(2))/(2+sqrt(2)) 0 1 - 1/(2+sqrt(2))]

3×3 Matrix{Float64}:
 -0.707107  0.0  0.707107
  0.0       1.0  0.0
  0.707107  0.0  0.707107

In [9]:
A2 = P*A

3×2 Matrix{Float64}:
 1.41421  0.707107
 0.0      2.0
 0.0      0.707107

In [12]:
Qt1 = copy(P);

In [13]:
z = A2[2:end,2]

2-element Vector{Float64}:
 2.0
 0.7071067811865475

In [14]:
e1 = [1.0;0.0]

2-element Vector{Float64}:
 1.0
 0.0

In [15]:
v = norm(z,2)*e1 - z

2-element Vector{Float64}:
  0.12132034355964239
 -0.7071067811865475

In [17]:
P = Matrix{Float64}(I,2,2) - (2.0/(v'*v))*(v*v')

2×2 Matrix{Float64}:
 0.942809   0.333333
 0.333333  -0.942809

In [19]:
Qt2 = Matrix{Float64}(I,3,3);
Qt2[2:end,2:end] = P
Qt2

3×3 Matrix{Float64}:
 1.0  0.0        0.0
 0.0  0.942809   0.333333
 0.0  0.333333  -0.942809

In [24]:
R = Qt2*Qt1*A

3×2 Matrix{Float64}:
 1.41421   0.707107
 0.0       2.12132
 0.0      -8.88178e-16

In [25]:
Q = Qt1*Qt2

3×3 Matrix{Float64}:
 -0.707107  0.235702  -0.666667
  0.0       0.942809   0.333333
  0.707107  0.235702  -0.666667

In [26]:
Q'*Q

3×3 Matrix{Float64}:
 1.0  0.0          0.0
 0.0  1.0          1.11022e-16
 0.0  1.11022e-16  1.0

In [27]:
Q*R

3×2 Matrix{Float64}:
 -1.0  5.18736e-17
  0.0  2.0
  1.0  1.0

In [28]:
A ≈ Q*R

true

In [52]:
A = [-1 2 3;3 -1 2;-1 0 1;0 1 1;-1 -1 1]

5×3 Matrix{Int64}:
 -1   2  3
  3  -1  2
 -1   0  1
  0   1  1
 -1  -1  1

In [53]:
m,n = size(A);
e1 = [1;0;0;0;0];
z = A[:,1];
v = norm(z,2)*e1 - z
β = 2 / (v'*v);
P = Matrix{Float64}(I,m,m) - β * (v * v') 

5×5 Matrix{Float64}:
 -0.288675  0.866025  -0.288675   0.0  -0.288675
  0.866025  0.418007   0.193998   0.0   0.193998
 -0.288675  0.193998   0.935334   0.0  -0.0646659
  0.0       0.0        0.0        1.0   0.0
 -0.288675  0.193998  -0.0646659  0.0   0.935334

In [54]:
P*A

5×3 Matrix{Float64}:
  3.4641       -1.1547    0.288675
 -2.22045e-16   1.12005   3.82209
  1.38778e-17  -0.706682  0.392638
  0.0           1.0       1.0
  0.0          -1.70668   0.392638

In [55]:
P' == P

true

In [56]:
P*P ≈ round.(abs.(P*P))

true

In [57]:
round.(abs.(P*P))

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [58]:
function hhzero(z)
    m = size(z)[1];
    e1 = zeros(m);
    e1[1] = 1.0;
    v = norm(z,2)*e1 - z;
    β = 2 / (v'*v);
    P = Matrix{Float64}(I,m,m) - β * (v * v')
end

hhzero (generic function with 1 method)

In [59]:
QA = P*A

5×3 Matrix{Float64}:
  3.4641       -1.1547    0.288675
 -2.22045e-16   1.12005   3.82209
  1.38778e-17  -0.706682  0.392638
  0.0           1.0       1.0
  0.0          -1.70668   0.392638

In [60]:
hhzero(QA[2:end,2])

4×4 Matrix{Float64}:
  0.470514  -0.296866  0.420084  -0.71695
 -0.296866   0.833557  0.235527  -0.40197
  0.420084   0.235527  0.666714   0.568814
 -0.71695   -0.40197   0.568814   0.0292158

In [61]:
A

5×3 Matrix{Int64}:
 -1   2  3
  3  -1  2
 -1   0  1
  0   1  1
 -1  -1  1

In [62]:
function hhqr!(A)
    m,n = size(A);
    Q = Matrix{Float64}(I,m,m);
    for k = 1:n
        z = A[k:end,k];
        Q[k:m,k:m] = hhzero(z);
        A = Q*A;
    end
    Q = Q';
    return Q, A
end

hhqr! (generic function with 1 method)

In [63]:
Q, A = hhqr!(A);