# Matrix Multiplication

### JMG

In [1]:
A = [-1.0 2.0 1.0; 1.0 0.0 -2.0;-3.0 -1.0 2.0]

3×3 Matrix{Float64}:
 -1.0   2.0   1.0
  1.0   0.0  -2.0
 -3.0  -1.0   2.0

In [2]:
B = [2.0 -1.0 2.0; 1.0 0.0 1.0;-1.0 1.0 -1.0]

3×3 Matrix{Float64}:
  2.0  -1.0   2.0
  1.0   0.0   1.0
 -1.0   1.0  -1.0

In [3]:
A*B

3×3 Matrix{Float64}:
 -1.0   2.0  -1.0
  4.0  -3.0   4.0
 -9.0   5.0  -9.0

In [4]:
using LinearAlgebra

In [5]:
(A*B)[2,1]

4.0

In [6]:
dot(A[2,:],B[:,1])

4.0

In [7]:
?dot

search: dot @__dot__ stdout DEPOT_PATH adjoint Adjoint adjoint! fieldcount



```
dot(x, y)
x ⋅ y
```

Compute the dot product between two vectors. For complex vectors, the first vector is conjugated.

`dot` also works on arbitrary iterable objects, including arrays of any dimension, as long as `dot` is defined on the elements.

`dot` is semantically equivalent to `sum(dot(vx,vy) for (vx,vy) in zip(x, y))`, with the added restriction that the arguments must have equal lengths.

`x ⋅ y` (where `⋅` can be typed by tab-completing `\cdot` in the REPL) is a synonym for `dot(x, y)`.

# Examples

```jldoctest
julia> dot([1; 1], [2; 3])
5

julia> dot([im; im], [1; 1])
0 - 2im

julia> dot(1:5, 2:6)
70

julia> x = fill(2., (5,5));

julia> y = fill(3., (5,5));

julia> dot(x, y)
150.0
```

---

```
dot(x, A, y)
```

Compute the generalized dot product `dot(x, A*y)` between two vectors `x` and `y`, without storing the intermediate result of `A*y`. As for the two-argument [`dot(_,_)`](@ref), this acts recursively. Moreover, for complex vectors, the first vector is conjugated.

!!! compat "Julia 1.4"
    Three-argument `dot` requires at least Julia 1.4.


# Examples

```jldoctest
julia> dot([1; 1], [1 2; 3 4], [2; 3])
26

julia> dot(1:5, reshape(1:25, 5, 5), 2:6)
4850

julia> ⋅(1:5, reshape(1:25, 5, 5), 2:6) == dot(1:5, reshape(1:25, 5, 5), 2:6)
true
```


In [8]:
(A*B)[:,1]

3-element Vector{Float64}:
 -1.0
  4.0
 -9.0

In [9]:
B[1,1]*A[:,1] + B[2,1]*A[:,2] + B[3,1]*A[:,3]

3-element Vector{Float64}:
 -1.0
  4.0
 -9.0