In [1]:
# if necessary, run the following:
#using Pkg;
#Pkg.activate(".");
#Pkg.instantiate();

# Introduction to Julia for Numerical Analysis

## Julia Arithmetic

It is straightforward to use Julia "as a calculator" for simple arithmetic. For example:

In [2]:
2 + 2

4

In [3]:
7 - 3

4

In [4]:
2 * 5

10

In [5]:
9 / 3

3.0

In [6]:
2 * (17 - 3) + 8 # Note order of operations

36

In [7]:
4^2

16

In [8]:
sqrt(4) # note that sqrt is a function and we will discuss functions more later 

2.0

Note that this can also be obtained with

In [9]:
4^(1/2)

2.0

or even with

In [10]:
4^0.5

2.0

It is useful to have some awareness of the fact that Julia distinguishes between different types of numerical values. Observe:

In [11]:
typeof(4) # in this case 4 is an integer of type Int64

Int64

In [12]:
typeof(4.0) # in this case 4.0 is an float of type Float64

Float64

While it is possible to carry out arithmetical operations on numbers of different types such as

In [13]:
1 + 1.3

2.3

it is better to avoid "type mixing" whenever possible. For example, the previous calculation is better computed as 

In [14]:
1.0 + 1.3

2.3

It is also possible to work with rational numbers in Julia. For example:

In [15]:
9 // 3

3//1

In [16]:
typeof(9 // 3)

Rational{Int64}

In [17]:
1 // 2 + 5 // 2

3//1

In [18]:
2 * (3 // 2)

3//1

In [19]:
7 // 3 - 1 // 5

32//15

To learn more about numerical types in Julia go [here](https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/).

## Working with Variables

In Julia it is simple to assign a value to a variable:

In [20]:
x = 2.5 # the variable is x and its value is 2.5

2.5

In [21]:
typeof(x)

Float64

In [22]:
y = 5 # the variable is y and its value is 5

5

In [23]:
typeof(y)

Int64

Then we can manipulate variables just as with numbers:

In [24]:
x + x

5.0

In [25]:
2*x

5.0

In [26]:
x^2

6.25

In [27]:
y - 2y # note that we don't always need the * for multiplication

-5

In [28]:
x*y

12.5

In [29]:
x + y

7.5

In [30]:
y / x

2.0

In [31]:
x^y

97.65625

One thing that is cool about Julia is that you can use unicode names such as Greek letters and other symbols to represent variables. For example:

In [32]:
α = 10.0
🐼 = 0.4

0.4

In [33]:
α * 🐼

4.0

For a list of unicode characters and the corresponding command, see [here](https://docs.julialang.org/en/v1/manual/unicode-input/).

## Vectors and Matrices in Julia

Here is how to define a vector in Julia. 

In [34]:
v1 = [1,5,3,2,8]

5-element Vector{Int64}:
 1
 5
 3
 2
 8

Observe the type of the vector

In [35]:
typeof(v1)

Vector{Int64} (alias for Array{Int64, 1})

We can request the length of a vector

In [36]:
length(v1)

5

We can also request the size of a vector. This is more useful later when we look at matrices. 

In [37]:
size(v1)

(5,)

It is easy to access the individual entries (*i.e.*, elements) of a vector. For example,  

In [38]:
v1[1]

1

In [39]:
v1[3]

3

We can also access multiple entries of a vector. This is sometimes called "slicing". For example,

In [40]:
v1[2:4]

3-element Vector{Int64}:
 5
 3
 2

You can use indexing and slicing to assign different values to entries in a vector. For example, 

In [41]:
v1[1] = 0

0

In [42]:
v1

5-element Vector{Int64}:
 0
 5
 3
 2
 8

There is something that you have to be careful about. Vectors are **immutable**. The following example illustrates the consequences of this that are relevant to us in this course. 

In [43]:
a1 = v1 # we create a variable a1 and assign to it the existing vector v1

5-element Vector{Int64}:
 0
 5
 3
 2
 8

Now we will change the value of an entry in a1:

In [44]:
a1[1] = 4

4

In [45]:
a1

5-element Vector{Int64}:
 4
 5
 3
 2
 8

The point is that changing a1 will also change v1 as shown below:

In [46]:
v1

5-element Vector{Int64}:
 4
 5
 3
 2
 8

If we want to assign a new variable to an existing vector and make changes without changing the original we have to use coying. For example,

In [47]:
b1 = copy(v1)

5-element Vector{Int64}:
 4
 5
 3
 2
 8

In [48]:
b1[1] = 0

0

The vector b1 changes. 

In [49]:
b1

5-element Vector{Int64}:
 0
 5
 3
 2
 8

But v1 does not.

In [50]:
v1

5-element Vector{Int64}:
 4
 5
 3
 2
 8

In [51]:
2*v1

5-element Vector{Int64}:
  8
 10
  6
  4
 16

In [52]:
2.0*v1

5-element Vector{Float64}:
  8.0
 10.0
  6.0
  4.0
 16.0

Here's a matrix

In [3]:
A = [1.0 -2.0 3.0;5.0 8.0 6.0;7.0 -4.0 8.0]

3×3 Matrix{Float64}:
 1.0  -2.0  3.0
 5.0   8.0  6.0
 7.0  -4.0  8.0

We can multiply a vector by a matrix:

In [5]:
x = [-1.0,2.0,-3.0]
A*x

3-element Vector{Float64}:
 -14.0
  -7.0
 -39.0

We will introduce further matrix computations in Julia later. 

## Basic Programming Constructs

Among the most basic programming constructs are conditional statements and loops. We will illustrate some simple ones here. 

### Conditionals

In [28]:
x = 10.5
if x > 1.0
    println("x is greater than one")
end

x is greater than one


In [29]:
if x > 1.0
    println("x is greater than one")
else
    println("x is not greater than one")
end

x is greater than one


In [30]:
if x >= 0.0 && x <= 1.0
    println("x is nonnegative and less than one")
elseif x > 1.0
    println("x is greater than one")
else
    println("x is negative")
end

x is greater than one


### Loops

In [31]:
x = [-4.0,3.0,-2.0,1.5]
n = length(x)
for i in 1:n
    if x[i] < 0.0
        val = x[i];
        println("x = $val is negative")
    end
end
    

x = -4.0 is negative
x = -2.0 is negative


In [32]:
for xi in x
    if xi < 0.0
        println("x = $xi is negative")
    end
end

x = -4.0 is negative
x = -2.0 is negative


Here's a nested loop

In [36]:
A = [1.0 -2.0 3.0;5.0 8.0 6.0;7.0 -4.0 8.0]
n,m = size(A)
for i = 1:n
    for j = 1:m
        val = A[i,j];
        if val < 0.0
          println("x = $val is negative")
        end
    end
end

x = -2.0 is negative
x = -4.0 is negative


In [37]:
for aij in A
    if aij < 0.0
          println("x = $aij is negative")
        end
end

x = -2.0 is negative
x = -4.0 is negative


Later we will also look at while loops

## Functions in Julia

In [38]:
f(x) = x^2;

In [39]:
f(2)

4

In [40]:
f(-2)

4

In [41]:
x = [-2, -1, 0, 1, 2, 3]

6-element Vector{Int64}:
 -2
 -1
  0
  1
  2
  3

In [42]:
y = zeros(length(x))

6-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [45]:
for i=1:length(x)
    y[i] = f(x[i])
end

In [46]:
y

6-element Vector{Float64}:
 4.0
 1.0
 0.0
 1.0
 4.0
 9.0

In [47]:
for xi in x
    y[i] = f(xi)
end

LoadError: UndefVarError: i not defined

In [48]:
i = 1
for xi in x
    y[i] = f(xi)
    i = i+1
end

In [49]:
y

6-element Vector{Float64}:
 4.0
 1.0
 0.0
 1.0
 4.0
 9.0

In [50]:
y = [f(xi) for xi in x]

6-element Vector{Int64}:
 4
 1
 0
 1
 4
 9

In [51]:
y = f.(x)

6-element Vector{Int64}:
 4
 1
 0
 1
 4
 9

In [52]:
y = f(x)

LoadError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:718
  ^(::LinearAlgebra.UniformScaling, ::Number) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/uniformscaling.jl:298
  ^(::LinearAlgebra.Symmetric{var"#s832", S} where {var"#s832"<:Real, S<:(AbstractMatrix{var"#s832"} where var"#s832"<:var"#s832")}, ::Integer) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:868
  ...

In [53]:
f(x) = x.^2

f (generic function with 1 method)

In [54]:
y = f(x)

6-element Vector{Int64}:
 4
 1
 0
 1
 4
 9

In [55]:
function g(x::Int64)
    x^2
end

g (generic function with 1 method)

In [56]:
function g(x::Vector{Int64})
    x.^2
end

g (generic function with 2 methods)

In [57]:
g(-1)

1

In [58]:
g([-1,-2,3,6])

4-element Vector{Int64}:
  1
  4
  9
 36

In [59]:
g(-1.0)

LoadError: MethodError: no method matching g(::Float64)
Closest candidates are:
  g(::Int64) at In[55]:1
  g(::Vector{Int64}) at In[56]:1

In [60]:
f(-1.0)

1.0

In [61]:
function find_root(a_val,N,x0)
    for i=1:N
        x0 = 0.5*(x0 + a_val/x0)
    end
    return x0
end

find_root (generic function with 1 method)

In [62]:
sq_approx = find_root(2.0,3,1.25)

1.4142135629622978

In [63]:
sqrt(2)

1.4142135623730951